<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

//PARTE DEL TEST
class GestionCamion extends Model
{
  protected $table="dbo.bodega_id_ofertas_camion";
  public $timestamps=false;
  protected $fillable = [
      'id_camion', 'codigo', 'codigo2', 'tipo_documento', 'descripcion', 'contenido', 'clasif_mercancia',
      'proveedor', 'marca_origen',
      'transporte_via',
      'pais_origen',
      'estado',
      'codigo_aux',
      'fecha_cierre',
      'monto_unitario',
      'monto_cierre',
      'fecha_embarque1',
      'fecha_embarque2',
      'fecha_llegada1',
      'fecha_llegada2',
      'fecha_embarque',
      'fecha_llegada_estimada',
      'fecha_llegada',
      'fecha_pago',
      'fecha_produccion',
      'fecha_produccion2',
      'fecha_vencimiento',
      'fecha_vencimiento2',
      'fecha_declaracion',
      'fecha_transbordo',
      'fecha_descarga',
      'fecha_devolucion_contenedor',
      'fecha_cumplimiento',
      'fecha_finalizacion',
      'resolucion_sanitaria',
      'fecha_resolucion',
      'observacion_fecha',
      'estado_pagado',
      'forma_pago',
      'despues_dias',
      'despues_fecha',
      'tipo_moneda',
      'cantidad_unidades',
      'tipo_unidades',
      'declara_origen',
      'declara_zona_ext',
      'declara_zona_exp',
      'declara_zona_franca',
      'declara_region',
      'declara_tramite',
      'declara_doc_ingreso',
      'declara_tipo_transp',
      'declara_empresa_transp',
      'declara_pais_origen',
      'declara_pais_procedencia',
      'declara_puerto_embarque',
      'declara_trasb_ext',
      'declara_trasb_nal',
      'declara_almacen',
      'declara_almacen_ubic',
      'declara_garantia',
      'declara_clausula',
      'valor_unidad',
      'valor_flete',
      'valor_seguro',
      'valor_fob',
      'recargo_flete',
      'valor_total',
      'valor_total_nal',
      'sucursal',
      'tratamiento_camion',
      'lugar_arribo',
      'cierre_items',
      'cierre_cantidad',
      'cierre_gastos',
      'factura_nro',
      'ingreso_cif',
      'ingreso_zeta',
      'ingreso_zeta_fecha',
      'ingreso_bultos',
      'ingreso_cantidad',
      'ingreso_tipo_cambio',
      'observaciones',
      'i_user',
      'i_date',
      'i_user_cierre',
      'i_date_cierre',
      'doc_contenedor',
      'doc_bl',
      'forward',
      'forward_fecha',
      'forward_compromiso',
      'swift',
      'switf_fecha',
      'pagado',
      'pagado_fecha',
      'naviera',
      'agencia',
      'transporte_nombre',
      'gerencial_saldo',
      'gerencial_utilidad',
      'gerencial_fecha',
      'contable_tipo_cambio',
      'bloqueo_2',
      'bloqueo_camion',
    ];
}
